# Generated by Django 4.0 on 2024-11-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('days', models.IntegerField()),
                ('person', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
