# Generated by Django 4.0 on 2024-11-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tourist_app', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pid',
            field=models.ForeignKey(db_column='pid', null=True, on_delete=django.db.models.deletion.CASCADE, to='tourist_app.places'),
        ),
        migrations.AddField(
            model_name='booking',
            name='uid',
            field=models.ForeignKey(db_column='uid', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
