# Generated by Django 4.0 on 2025-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0004_booking_pid_booking_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media2/'),
        ),
    ]
